version: '3.8'

services:
  database:
    image: postgres:16
    ports:
      - "3306:3306"
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: postgres
    volumes:
      -medi_data:/etc/postgres/data

  backend:
    image: medi-backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=



  frontend:
    image: medi-frontend
    ports:
      - "8080:80"
    

  